= STrello - веб-приложение для управления задачами =
:source-highlighter: rouge
:doctype: book
:toc:
:toc-title: Оглавление

== Что это

Это простое веб-приложение для управления списком задач.
Создано в учебных целях. 

Функциональные возможности:
* просмотр полного списка задач;
* отбор задач по дате и/или исполнителю;
* добавление задачи в список;

Демо-версия развернута оп адресу: http://167.172.170.10:8080/

== Сборка проекта

Для сборки используется https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.2/[maven 3.6.2], запускаемый через обертку https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.5/[maven-wrapper 0.5.5]. Maven-wrapper при запуске скачивает maven и необходимые зависимости, описанные в файле pom.xml.

.Сборка в Windows
[source,cmd]
----
mvnw.cmd clean package 
----

.Сборка в Linux/BSD
[source,sh]
----
./mvnw clean package 
----

Результат сборки - WAR-файл.

== Запуск приложения на локальной машине

По команде

[source,sh]
----
./mvnw tomcat7:run-war
----

Будет выполнена сборка проекта, запуск встроенного контейнера tomcat7 (предоставляется плагином https://tomcat.apache.org/maven-plugin-trunk/index.html[Apache Tomcat Maven Plugin]) и разворачивание собранного WAR на этом локальном сервере. Развернутое приложение будет доступно по адресу http://localhost:8090/. 

== Зависимости сборки

Зависимости будут скачаны автоматически из репозитория **maven central** в процессе сборки.



== Устройство приложения

